version: '3'
services:
  svdb:
    image: postgres:latest
    container_name: svdb
    ports:
      - '6505:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env

  redis:
    image: redis
    container_name: svdb-redis
    ports:
    - '6379:6379'
    networks:
      - svdb_network
  
volumes:
    progresDB:
  
networks:
  svdb_network:
    driver: bridge