export const TagsEnum = {
    GAMESHOW: 'Gameshow',
    GAMING: 'Gaming',
    EXTREME: 'Extreme',
    FOOTBALL: 'Football',
    CHALLENGE: 'Challenge',
    REACT: 'React',
    HIDE_SEEK: 'Hide & Seek',
    FIFA: 'FIFA',
    GTA5: 'GTA 5',
    MINECRAFT: 'Minecraft',
    AMONGUS: 'Among Us',
    MUSIC: 'Music',
    CHRISTMAS: 'Christmas',
    HOLIDAY: 'Holiday',
    PUB_GOLF: 'Pub Golf',
    ROAD_TRIP: 'Road Trip',
    ROAST: 'Roast',
    THROW_A_DART: 'Throw a Dart',
    TINDER: 'Tinder',
    COOK_OFF: 'Cook Off',
    HOURS_24: '24 Hours',
    HOTELS: 'Hotels',
    FALL_GUYS: 'Fall Guys',
    GUESS_WHO: 'Guess Who',
    RATING: 'Rating',
    SIDEMEN_VS: 'Sidemen Vs',
    SILENT_LIBRARY: 'Silent Library',
    TRY_NOT_TO_MOVE: 'Try Not to Move',
    MUKBANG: 'Mukbang',
    BLIND_DATE: 'Blind Date',
    IN_REAL_LIFE: 'In Real Life',
    VS_20: '20vs1',
    BAKE_OFF: 'Bake off',
    GOT_TALENT: 'Got Talent',
    F1_23_MY_TEAM: 'F1 23 My Team',
    BREWPUB_SIMULATOR: 'Brewpub Simulator',
    ITS_ONLY_MONEY: 'Its Only Money',
    ABANDONED_CHALLENGE: 'Abandoned Challenge',
    CALORIES_CHALLENGE: 'Calories Challenge',
    MYSTERY_BOX: 'Mystery Box',
    CAMPING: 'Camping',
    CHRISTMAS_DAY: 'Christmas Day',
    NEW_YEARS_EVE: 'New Years Eve',
    WATERPARK: 'Waterpark',
    DEAL_OR_NOT_A_DEAL: 'Deal Or Not a Deal',
    RACE_ACROSS: 'Race Across',
    CAR_FOR_SALE_SIMULATOR_2023: 'Car For Sale Simulator 2023',
    I_SURVIVED: 'I Survived',
    RESTAURANT: 'Restaurant',
    GREATEST_MOMENTS: 'Greatest Moments',
    SUBNAUTICA_BELOW_ZERO: 'Subnautica: Below Zero',
    CALL_OF_DUTY: 'Call Of Duty',
    MEME_OLYMPICS: 'Meme Olympics',
    HOT_VS_COLD: 'Hot vs Cold',
    BIG_FAT_QUIZ: 'Big Fat Quiz',
    FORFEIT_WHEEL_OF_FORTUNE: 'Forfeit Wheel of Fortune',
    W2S_CANCELLED_MOMENTS: 'W2S CANCELLED MOMENTS',
    ULTIMATE_BACHELOR: 'Ultimate Bachelor'
  };

  export const SeriesEnum = {
    CALORIES_CHALLENGE: 'Calories Challenge',
    GOT_TALENT: 'Got Talent',
    DEAL_OR_NOT_A_DEAL: 'Deal Or Not a Deal',
    BAKE_OFF: 'Bake off',
    MEME_OLYMPICS: 'Meme Olympics',
    BIG_FAT_QUIZ: 'Big Fat Quiz',
    GREATEST_MOMENTS: 'Greatest Moments',
    RACE_ACROSS: 'Race Across',
    MYSTERY_BOX: 'Mystery Box',
    NEW_YEARS_EVE: 'New Years Eve',
    TINDER: 'Tinder',
    TRY_NOT_TO_MOVE: 'Try Not to Move',
    MUKBANG: 'Mukbang',
    CAMPING: 'Camping',
    ROAST: 'Roast',
    _20VS1: '20vs1',
    ABANDONED_CHALLENGE: 'Abandoned Challenge',
    SIDEMEN_VS: 'Sidemen Vs',
    ULTIMATE_BACHELOR: 'Ultimate Bachelor',
    ROAD_TRIP: 'Road Trip',
    HIDE_AND_SEEK: 'Hide & Seek',
    THROW_A_DART: 'Throw a Dart',
    GAMESHOW: 'Gameshow',
    FORFEIT_WHEEL_OF_FORTUNE: 'Forfeit Wheel of Fortune',
    BLIND_DATE: 'Blind Date',
    CHRISTMAS: 'Christmas',
    COOK_OFF: 'Cook Off',
    SILENT_LIBRARY: 'Silent Library',
    HOLIDAY: 'Holiday',
    _24_HOURS: '24 Hours',
    PUB_GOLF: 'Pub Golf',
    HOT_VS_COLD: 'Hot vs Cold'
};

export const GamesEnum = {
    SUBNAUTICA_BELOW_ZERO: 'Subnautica: Below Zero',
    CALL_OF_DUTY: 'Call Of Duty',
    F1_23: 'F1 23',
    BREWPUB_SIMULATOR: 'Brewpub Simulator',
    ITS_ONLY_MONEY: 'Its Only Money',
    FALL_GUYS: 'Fall Guys',
    FIFA: 'FIFA',
    GTA5: 'GTA 5',
    MINECRAFT: 'Minecraft',
    AMONGUS: 'Among Us',
};